changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧹 Cleanup & Maintenance
      labels:
        - chore
        - refactor
        - documentation
    - title: 📦 Other Changes
      labels:
        - "*"